name: Newsletter
on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Subject'
        required: true

jobs:
  newsletter:
    runs-on: ubuntu-latest
    name: Send newsletter
    steps:
    - name: Send newsletter
      uses: KNawm/newsletter-action@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        subject: ${{ github.event.inputs.subject }}
        list_id: '81f44a3f-f1c2-4f47-a9a9-df79dd32d246'
        suppression_group_id: 22584
        sender_id: 1057550
